export type LanguagesSupported =
  | "ab"
  | "ace"
  | "ach"
  | "af"
  | "sq"
  | "alz"
  | "am"
  | "ar"
  | "hy"
  | "as"
  | "awa"
  | "ay"
  | "az"
  | "ban"
  | "bm"
  | "ba"
  | "eu"
  | "btx"
  | "bts"
  | "bbc"
  | "be"
  | "bem"
  | "bn"
  | "bew"
  | "bho"
  | "bik"
  | "bs"
  | "br"
  | "bg"
  | "bua"
  | "yue"
  | "ca"
  | "ceb"
  | "ny"
  | "zh-CN"
  | "zh-TW"
  | "cv"
  | "co"
  | "crh"
  | "hr"
  | "cs"
  | "da"
  | "din"
  | "dv"
  | "doi"
  | "dov"
  | "nl"
  | "dz"
  | "en"
  | "eo"
  | "et"
  | "ee"
  | "fj"
  | "fil"
  | "tl"
  | "fi"
  | "fr"
  | "fr-FR"
  | "fr-CA"
  | "fy"
  | "ff"
  | "gaa"
  | "gl"
  | "lg"
  | "ka"
  | "de"
  | "el"
  | "gn"
  | "gu"
  | "ht"
  | "cnh"
  | "ha"
  | "haw"
  | "iw"
  | "he"
  | "hil"
  | "hi"
  | "hmn"
  | "hu"
  | "hrx"
  | "is"
  | "ig"
  | "ilo"
  | "id"
  | "ga"
  | "it"
  | "ja"
  | "jw"
  | "jv"
  | "kn"
  | "pam"
  | "kk"
  | "km"
  | "cgg"
  | "rw"
  | "ktu"
  | "gom"
  | "ko"
  | "kri"
  | "ku"
  | "ckb"
  | "ky"
  | "lo"
  | "ltg"
  | "la"
  | "lv"
  | "lij"
  | "li"
  | "ln"
  | "lt"
  | "lmo"
  | "luo"
  | "lb"
  | "mk"
  | "mai"
  | "mak"
  | "mg"
  | "ms"
  | "ms-Arab"
  | "ml"
  | "mt"
  | "mi"
  | "mr"
  | "chm"
  | "mni-Mtei"
  | "min"
  | "lus"
  | "mn"
  | "my"
  | "nr"
  | "new"
  | "ne"
  | "nso"
  | "no"
  | "nus"
  | "oc"
  | "or"
  | "om"
  | "pag"
  | "pap"
  | "ps"
  | "fa"
  | "pl"
  | "pt"
  | "pt-PT"
  | "pt-BR"
  | "pa"
  | "pa-Arab"
  | "qu"
  | "rom"
  | "ro"
  | "rn"
  | "ru"
  | "sm"
  | "sg"
  | "sa"
  | "gd"
  | "sr"
  | "st"
  | "crs"
  | "shn"
  | "sn"
  | "scn"
  | "szl"
  | "sd"
  | "si"
  | "sk"
  | "sl"
  | "so"
  | "es"
  | "su"
  | "sw"
  | "ss"
  | "sv"
  | "tg"
  | "ta"
  | "tt"
  | "te"
  | "tet"
  | "th"
  | "ti"
  | "ts"
  | "tn"
  | "tr"
  | "tk"
  | "ak"
  | "uk"
  | "ur"
  | "ug"
  | "uz"
  | "vi"
  | "cy"
  | "xh"
  | "yi"
  | "yo"
  | "yua"
  | "zu";

export const LanguagesSupportedMap: Record<LanguagesSupported, string> = {
  ab: "Abkhaz",
  ace: "Acehnese",
  ach: "Acholi",
  af: "Afrikaans",
  sq: "Albanian",
  alz: "Alur",
  am: "Amharic",
  ar: "Arabic",
  hy: "Armenian",
  as: "Assamese",
  awa: "Awadhi",
  ay: "Aymara",
  az: "Azerbaijani",
  ban: "Balinese",
  bm: "Bambara",
  ba: "Bashkir",
  eu: "Basque",
  btx: "Batak Karo",
  bts: "Batak Simalungun",
  bbc: "Batak Toba",
  be: "Belarusian",
  bem: "Bemba",
  bn: "Bengali",
  bew: "Betawi",
  bho: "Bhojpuri",
  bik: "Bikol",
  bs: "Bosnian",
  br: "Breton",
  bg: "Bulgarian",
  bua: "Buryat",
  yue: "Cantonese",
  ca: "Catalan",
  ceb: "Cebuano",
  ny: "Chichewa",
  "zh-CN": "Chinese (Simplified)",
  "zh-TW": "Chinese (Traditional)",
  cv: "Chuvash",
  co: "Corsican",
  crh: "Crimean Tatar",
  hr: "Croatian",
  cs: "Czech",
  da: "Danish",
  din: "Dinka",
  dv: "Divehi",
  doi: "Dogri",
  dov: "Dombe",
  nl: "Dutch",
  dz: "Dzongkha",
  en: "English",
  eo: "Esperanto",
  et: "Estonian",
  ee: "Ewe",
  fj: "Fijian",
  fil: "Filipino",
  tl: "Filipino (Tagalog)",
  fi: "Finnish",
  fr: "French",
  "fr-FR": "French (France)",
  "fr-CA": "French (Canadian)",
  fy: "Frisian",
  ff: "Fulfulde",
  gaa: "Ga",
  gl: "Galician",
  lg: "Ganda (Luganda)",
  ka: "Georgian",
  de: "German",
  el: "Greek",
  gn: "Guarani",
  gu: "Gujarati",
  ht: "Haitian Creole",
  cnh: "Hakha Chin",
  ha: "Hausa",
  haw: "Hawaiian",
  iw: "Hebrew",
  he: "Hebrew",
  hil: "Hiligaynon",
  hi: "Hindi",
  hmn: "Hmong",
  hu: "Hungarian",
  hrx: "Hunsrik",
  is: "Icelandic",
  ig: "Igbo",
  ilo: "Iloko",
  id: "Indonesian",
  ga: "Irish",
  it: "Italian",
  ja: "Japanese",
  jw: "Javanese",
  jv: "Javanese",
  kn: "Kannada",
  pam: "Kapampangan",
  kk: "Kazakh",
  km: "Khmer",
  cgg: "Kiga",
  rw: "Kinyarwanda",
  ktu: "Kituba",
  gom: "Konkani",
  ko: "Korean",
  kri: "Krio",
  ku: "Kurdish (Kurmanji)",
  ckb: "Kurdish (Sorani)",
  ky: "Kyrgyz",
  lo: "Lao",
  ltg: "Latgalian",
  la: "Latin",
  lv: "Latvian",
  lij: "Ligurian",
  li: "Limburgan",
  ln: "Lingala",
  lt: "Lithuanian",
  lmo: "Lombard",
  luo: "Luo",
  lb: "Luxembourgish",
  mk: "Macedonian",
  mai: "Maithili",
  mak: "Makassar",
  mg: "Malagasy",
  ms: "Malay",
  "ms-Arab": "Malay (Jawi)",
  ml: "Malayalam",
  mt: "Maltese",
  mi: "Maori",
  mr: "Marathi",
  chm: "Mari",
  "mni-Mtei": "Manipuri (Meitei)",
  min: "Minangkabau",
  lus: "Mizo",
  mn: "Mongolian",
  my: "Myanmar (Burmese)",
  nr: "Ndebele (South)",
  new: "Nepali (Newari)",
  ne: "Nepali",
  nso: "Northern Sotho",
  no: "Norwegian",
  nus: "Nuer",
  oc: "Occitan",
  or: "Odia",
  om: "Oromo",
  pag: "Pangasinan",
  pap: "Papiamento",
  ps: "Pashto",
  fa: "Persian",
  pl: "Polish",
  pt: "Portuguese",
  "pt-PT": "Portuguese (Portugal)",
  "pt-BR": "Portuguese (Brazilian)",
  pa: "Punjabi",
  "pa-Arab": "Punjabi (Arabic)",
  qu: "Quechua",
  rom: "Romani",
  ro: "Romanian",
  rn: "Rundi",
  ru: "Russian",
  sm: "Samoan",
  sg: "Sango",
  sa: "Sanskrit",
  gd: "Scots Gaelic",
  sr: "Serbian",
  st: "Sesotho",
  crs: "Seselwa Creole French",
  shn: "Shan",
  sn: "Shona",
  scn: "Sicilian",
  szl: "Silesian",
  sd: "Sindhi",
  si: "Sinhala",
  sk: "Slovak",
  sl: "Slovenian",
  so: "Somali",
  es: "Spanish",
  su: "Sundanese",
  sw: "Swahili",
  ss: "Swati",
  sv: "Swedish",
  tg: "Tajik",
  ta: "Tamil",
  tt: "Tatar",
  te: "Telugu",
  tet: "Tetum",
  th: "Thai",
  ti: "Tigrinya",
  ts: "Tswana",
  tn: "Tswana",
  tr: "Turkish",
  tk: "Turkmen",
  ak: "Twi",
  uk: "Ukrainian",
  ur: "Urdu",
  ug: "Uyghur",
  uz: "Uzbek",
  vi: "Vietnamese",
  cy: "Welsh",
  xh: "Xhosa",
  yi: "Yiddish",
  yo: "Yoruba",
  yua: "Yucatec Maya",
  zu: "Zulu",
};
